#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file

while IFS=':' read -r username _ userid groupid _ home_directory shell
do
  password=$(grep "^$username:" /etc/shadow | awk -F':' '{print $2}')
  user_info=$(grep "^$username:" /etc/passwd | awk -F':' '{print $5}')

  echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
