#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data

awk '{ count[$1" "$9]++ } END { for (data in count) { printf "%6d %s\n", count[data], data } }' apache-access.log | sort -rn
