#!/usr/bin/env bash
#Start manage_my_process
#Check if the manage_my_process is already running
PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"

start_process() {
    if [ -f "$PID_FILE" ]; then
        echo "$PROCESS_NAME is already running."
    else
        ./manage_my_process >/dev/null 2>&1 &
        echo -n $! > "$PID_FILE"
        echo "$PROCESS_NAME started"
    fi
}

stop_process() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
        echo "$PROCESS_NAME stopped"
    else
        echo "$PROCESS_NAME is not running."
    fi
}

restart_process() {

    echo "$PROCESS_NAME restarted"                                                                                                                     
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

