#!/usr/bin/env bash
# This script manages the manage_ my_process script

case "$1" in 
	start)
# Start manage_my_process
        ./manage_my_process &
# Create a file containing its PID in /var/run/my_process.pid 
        touch /var/run/my_process.pid 
	echo $! > /var/run/my_process.pid 
	echo "manage_my_process started"
	;;
stop)
# Stop manage_my _process
        kill "$(cat /var/run/my_process.pid)"
* Delete the file /var/run/my_process.pid 
        rm /var/run/my_process.pid 
        echo "manage_my_process stopped"
	;;
restart)
# Stop manage_my_process
        kill "$(cat /var/run/my _process.pid)"
# Delete the file var/run/my _process.pid
        rm /var/run/my_process.pid
# Start manage_my_process
        ./manage_my_process &
# Create a file contaihang its PID in /var/run/my_process.pid
        touch /var/run/my_process.pid  
	echo $! > /var/run/my_process.pid 
	echo "manage_my _process restarted"
	;;
*)
       echo "Usage: manage_my_process (start|stop|restart}"
       exit 1
       ;;
esac

exit 0
